/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeCaller */

#ifndef _Included_NativeCaller
#define _Included_NativeCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeCaller
 * Method:    callHistory
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)LCurrencyDataContainer;
 */
JNIEXPORT jobject JNICALL Java_NativeCaller_callHistory
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
